module.exports = {
  VERIFY_TOKEN: process.env.TANGLED_VERIFY_TOKEN,
  PAGE_ACCESS_TOKEN: process.env.TANGLED_PAGE_ACCESS_TOKEN,
  APIAPI_CLIENT_ACCESS_TOKEN: process.env.APIAPI_CLIENT_ACCESS_TOKEN,
  APIAPI_SESSION_ID: process.env.APIAPI_SESSION_ID
};
